project:
  type: website
  output-dir: docs

website:
  title: mall
  navbar:
    left:
      - href: reference/index.qmd
        text: Reference
      - sidebar:articles
  sidebar:
    - id: articles
      title: "Articles"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
      - text: "Databricks"
        href: articles/databricks.qmd

format:
  html:
    toc: true
    code-copy: true
    code-overflow: wrap