project:
  type: website
  output-dir: docs
  
execute: 
  freeze: true 
  eval: true

website:
  title: mall
  favicon: "figures/favicon/apple-touch-icon.png"
  navbar:
    logo: "figures/favicon/apple-touch-icon.png"
    left:
      - sidebar:articles    
      - href: reference/index.qmd
        text: Reference
    right:
      - icon: github
        href: https://github.com/edgararuiz/mall    
  sidebar:
    - id: articles
      title: "Articles"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
      - text: "Caching"
        href: articles/caching.qmd
      - text: "Databricks"
        href: articles/databricks.qmd        

format:
  html:
    toc: true
    code-copy: true
    code-overflow: wrap
    code-toos: true
    eval: false
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]

knitr:
  opts_chunk: 
    collapse: true
    comment: "#>"    