project:
  type: website
  output-dir: docs

website:
  title: mall
  navbar:
    left:
      - href: reference/index.qmd
        text: Reference

format:
  html:
    toc: true
    code-copy: true
    code-overflow: wrap