name: Python coverage

on: 
  push:
    branches: main
    
jobs:
  python-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt
      - name: Generate coverage report
        run: |
          pytest --cov=python --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: python/coverage/reports/
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: python/coverage1.xml,python/coverage2.xml,!python/cache
          flags: unittests
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
