on:
  push:
    branches: main
name: Quarto site

permissions: read-all

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Publish to GitHub Pages (and render)
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }